### ISSUE TITLE
Tests are failing in some circumstances

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/spectacle#307]
When I run tests locally, I'm seeing failures like:

```
  ● <Manager /> › should render the overview configuration when specified.

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -68,13 +68,14 @@
               <div
                 className="kxQqKR">
                 <styled.div
                   index={0}
                   onClick={[Function]}
    +              screen={0}
                   slideIndex={0}>
                   <div
    -                className="goGPmP"
    +                className="cAopeV"
                     onClick={[Function]}>
                     <MockSlide
                       appearOff={true}
                       export={false}
                       print={false}
    @@ -88,13 +89,14 @@
                   </div>
                 </styled.div>
                 <styled.div
                   index={1}
                   onClick={[Function]}
    +              screen={0}
                   slideIndex={0}>
                   <div
    -                className="gvZlT"
    +                className="gtMIIo"
                     onClick={[Function]}>
                     <MockSlide
                       appearOff={true}
                       export={false}
                       print={false}
    @@ -128,11 +130,12 @@
                 }
               }
               viewBox="0 0 512 512"
               width="30px">
               <path
    -            d="M73.143,329.143H0V512h182.857v-73.143H73.143V329.143z M0,182.857h73.143V73.143h109.715V0H0V182.857z M438.857,438.857 H329.143V512H512V329.143h-73.143V438.857z M329.143,0v73.143h109.715v109.715H512V0H329.143z" />
    +            d="M73.143,329.143H0V512h182.857v-73.143H73.143V329.143z M0,182.857h73.143V73.143h109.715V0H0V182.857z M438.857,438.857
    +                    H329.143V512H512V329.143h-73.143V438.857z M329.143,0v73.143h109.715v109.715H512V0H329.143z" />
             </svg>
           </Fullscreen>
           <Style
             rules={
               Object {

      at Object.<anonymous> (lib/components/manager.test.js:129:53)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:172:7)
      at internal/child_process.js:721:12
      at nextTickCallbackWith0Args (node.js:489:9)
      at process._tickCallback (node.js:418:13)
```

```console
$ node -v
node -v
v4.8.0
```

**Comment by exogen** [comment]
@stefvhuynh If you don't have the same failures on `master`, can you post the output of:

```console
$ npm ls react react-dom react-addons-test-utils jest
spectacle@2.0.0 /Users/brianbeck/Projects/Formidable/spectacle
├── jest@17.0.3
├── UNMET PEER DEPENDENCY markdown-to-react-components@0.2.3
├── react@15.4.2
├── react-addons-test-utils@15.4.1
└── react-dom@15.4.2
```

**Comment by exogen** [comment]
I rebooted my computer and now they work. Everything is terrible.
