### ISSUE TITLE
Image reference error in preloader for v2.1.0

### ISSUE THREAD

**Issue by travi** [FormidableLabs/spectacle#323]
https://travis-ci.org/travi/presentations/builds/236047671

```
/home/travis/build/travi/presentations/node_modules/spectacle/lib/utils/preloader.js:15
    var image = new Image();
                    ^
ReferenceError: Image is not defined
    at /home/travis/build/travi/presentations/node_modules/spectacle/lib/utils/preloader.js:15:21
    at /home/travis/build/travi/presentations/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/home/travis/build/travi/presentations/node_modules/lodash/_baseForOwn.js:13:20)
    at /home/travis/build/travi/presentations/node_modules/lodash/_createBaseEach.js:17:14
    at forEach (/home/travis/build/travi/presentations/node_modules/lodash/forEach.js:38:10)
    at preload (/home/travis/build/travi/presentations/node_modules/spectacle/lib/utils/preloader.js:14:25)
    at Object.<anonymous> (/home/travis/build/travi/presentations/src/example/presentation.js:36:1)
    at Module._compile (module.js:571:32)
    at loader (/home/travis/build/travi/presentations/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/travi/presentations/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/travi/presentations/test/example/smoke-test.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/home/travis/build/travi/presentations/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/travi/presentations/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/travis/build/travi/presentations/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/travi/presentations/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/travis/build/travi/presentations/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/travis/build/travi/presentations/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by travi** [comment]
I finally got back around to investigating this further. It looks like the `Image` that is intended for use here is the [Image constructor](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image). 

I'm seeing this error when running smoke tests against [jsdom](https://github.com/tmpvar/jsdom), which doesnt make the constructor available as a true global by default. When I tried to change the usage that fails to be `new window.Image()` instead of `new Image()`, the smoke tests passed successfully again. That told me that the fairly typical need to elevate jsdom properties was needed here, so I was able to get past this issue with the following addition to my jsdom configuration:

```js
// my preexisting config included the following
const dom = new JSDOM('<!doctype html><html><body></body></html>', {url: 'http://localhost'});

// adding this made the Image constructor available as a global
global.Image = dom.window.Image;
```
