### ISSUE TITLE
Docs: Postcss in react-static@5 fails CSS building

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/spectacle#857]
Probably will go away with #838 upgrade to react-static@7, but for how we're hitting this:

```sh
$ yarn prod:build
ERROR in ./node_modules/prismjs/themes/prism.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `dead`
    at error (/Users/rye/scm/fmd/spectacle/docs/node_modules/browserslist/index.js:37:11)
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/browserslist/index.js:222:9
    at Array.forEach (<anonymous>)
    at browserslist (/Users/rye/scm/fmd/spectacle/docs/node_modules/browserslist/index.js:196:13)
    at cleanBrowsersList (/Users/rye/scm/fmd/spectacle/docs/node_modules/caniuse-api/dist/utils.js:56:59)
    at setBrowserScope (/Users/rye/scm/fmd/spectacle/docs/node_modules/caniuse-api/dist/index.js:29:43)
    at Object.<anonymous> (/Users/rye/scm/fmd/spectacle/docs/node_modules/caniuse-api/dist/index.js:91:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .js] (/Users/rye/scm/fmd/spectacle/docs/node_modules/babel-register/lib/node.js:152:7)
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/webpack/lib/NormalModule.js:195:19
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/rye/scm/fmd/spectacle/docs/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/rye/scm/fmd/spectacle/docs/node_modules/postcss-loader/lib/index.js:187:9
 @ ./src/app.js 33:0-35
 @ ./src/index.js
```

See, e.g.: https://github.com/browserslist/browserslist/issues/266

Going to temporarily disable CSS minification.

## Task
- [ ] Fix build error
- [ ] Reenable css minification.

**Comment by ryan-roemer** [comment]
Should not block spectacle@6 release
